### ISSUE TITLE
renaming props of PodListResponse interface to plurals

### ISSUE THREAD

**Issue by rampall** [soheil555/fairOS-js#3]
since both properties return string arrays, renaming 
`pod_name` to `pod_names` and 
`shared_pod_name` => `shared_pod_names` 
would be more intuitive

**Comment by soheil555** [comment]
That'd be great.
But the  [FairOS-dfs ListPod API response](https://docs.fairos.fairdatasociety.org/api/index.html#tag/Pod/paths/~1v1~1pod~1ls/get) uses the singular form and the API client interfaces need to match the FairOS API responses structures.

**Comment by rampall** [comment]
Ah, makes sense then. I should file an issue there. 
Cool lib btw!

**Comment by soheil555** [comment]
I am so glad you liked the library.
